### ISSUE TITLE
organizing the lists

### ISSUE THREAD

**Issue by myrdd** [RequestPolicyContinued/subscriptions#1]
I'd like to organize the lists with comments.
I tried to add comment to a json file (see [here](https://github.com/RequestPolicyContinued/subscriptions/blob/00b2670bc6625b7ccad8881a329990b635c52262/official-allow_sameorg.json)) before I figured out that comments are not allowed or rather specified for json files. To organize the subscriptions it would be good to be able to add comments. A solution would be to have a file with comments and an automatic tool would remove the comments / convert to json.

**Comment by nodiscc** [comment]
Moved to https://github.com/RequestPolicyContinued/subscriptions/issues/29 and https://github.com/RequestPolicyContinued/subscriptions/issues/21
