### ISSUE TITLE
Copy lists from disconnect addon

### ISSUE THREAD

**Issue by nodiscc** [RequestPolicyContinued/subscriptions#18]
Sort and add destination domains inclued in https://github.com/disconnectme/disconnect/blob/master/firefox/content/disconnect.safariextension/opera/chrome/data/services.json

Part of https://github.com/RequestPolicyContinued/requestpolicy/issues/14

**Comment by nodiscc** [comment]
Firefox's new tracking protection feature uses Disconnect's lists: https://support.mozilla.org/en-US/kb/tracking-protection-firefox#w_what-is-tracking-protection. There is no point in duplicating it in RPContinued. A toogle switch for the Tracking Protection feature would be welcome on the RPC "Advanced preferences" pages.

Related to https://github.com/RequestPolicyContinued/requestpolicy/issues/628

**Comment by myrdd** [comment]
> A toogle switch for the Tracking Protection feature would be welcome on the RPC "Advanced preferences" pages.

Would you mind creating a new issue for such toggles, so that we don't forget them?
