### ISSUE TITLE
Duplicate rules in subscriptions

### ISSUE THREAD

**Issue by GdrjirfRtrUhYUdrjUMm** [RequestPolicyContinued/subscriptions#25]
This rule is a duplicate:
Allow | *.163.com | *.netease.com | allow_sameorg

I couldn't find any documentation about rules on multiple subscriptions. I searched previous issues for some of the domains and couldn't find any. I'm assuming the rules shouldn't be on multiple subscriptions but I appoligize if I'm incorrect. At least I tried to find an answer before filing the issue. These rules are duplicated on the allow_functionality and allow_sameorg subscriptions:

Allow | *.stackoverflow.com | *.sstatic.net
Allow | *.github.com | *.avatars0.githubusercontent.com
Allow | *.github.com | *.avatars3.githubusercontent.com
Allow | *.github.com | *.avatars2.githubusercontent.com
Allow | *.github.com | *.avatars1.githubusercontent.com
Allow | *.reddit.com | *.redditmedia.com
Allow | *.reddit.com | *.redditstatic.com
Allow | *.theonion.com | *.onionstatic.com
Allow | *.arstechnica.com | *.arstechnica.net
Allow | *.autodesk.com | *.autodesk.net
Allow | *.google.com | *.google.fr

**Comment by nodiscc** [comment]
You are right, these rules should only be in _allow_sameorg_.

**Comment by nodiscc** [comment]
- [ ] automate detection of duplicate rules in `allow_sameorg/allow_functionality`, remove them from allow_functionality
 - [ ] rename  `allow_sameorg` to `allow_functionality_sameorg`
