### ISSUE TITLE
live.com <--> microsoft.com

### ISSUE THREAD

**Issue by myrdd** [RequestPolicyContinued/subscriptions#39]
When first visiting `answers.microsoft.com` you're getting redirected to `login.live.com`, and back. See https://github.com/RequestPolicyContinued/requestpolicy/issues/756#issuecomment-173134175. @nodiscc isn't this a candidate for `allow_sameorg`? Which checks did you do before adding a rule to the list?

**Comment by nodiscc** [comment]
It is ok to add this rule to https://github.com/RequestPolicyContinued/subscriptions/blob/d463ae3106ad014aa5604ea6998d1079cc5040b1/official-allow_sameorg.json#L31. Can you send a quick patch? I'll get things in order if it's incomplete (don't bother cahnging the serials, etc, I will do it at merge). Thanks.

> Which checks did you do before adding a rule to the list?

Usually I check the WHOIS information for both domains and see if they match. In this case it is well known that live.com is a microsoft service.

**Comment by myrdd** [comment]
Thx for the info, and the quick reply.

> Can you send a quick patch?
> don't bother cahnging the serials, etc

As you wish. #40
