### ISSUE TITLE
Firefox Webextensions do not load with RequestPolicyContinued enabled

### ISSUE THREAD

**Issue by fiveNinePlusR** [RequestPolicyContinued/subscriptions#53]
As a consequence of the defaults of RequestPolicy/RequestPolicyContinued all webextensions do not load up in firefox and do not show the user any useful information as to why. 

There is a firefox bug here describing it: https://bugzilla.mozilla.org/show_bug.cgi?id=1298856

Ideally this would be fixed in both RequestPolicy and RequestPolicyContinued.

**Comment by myrdd** [comment]
> Ideally this would be fixed in both RequestPolicy and RequestPolicyContinued.

It's fixed in RP Legacy as I wrote here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1298856#c9
The issue for RPC (1.0 beta) is https://github.com/RequestPolicyContinued/requestpolicy/issues/813.
