### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by myrdd** [RequestPolicyContinued/subscriptions#57]
Copying from https://github.com/RequestPolicyContinued/requestpolicy/issues/830#issuecomment-313605518, I think one needs following rules to enable discord:

Policy | Origin | Destination
-- | -- | --
Allow | *.discordapp.com | *.discordapp.net
Allow | https://*.discordapp.com | wss://*.discord.gg
Allow | *.discordapp.com | *.discordapp.com

**Comment by Zero3K** [comment]
👍 

I hope to see it added soon.
