### ISSUE TITLE
Twitch VODs and Livestreams aren't loading with it enabled

### ISSUE THREAD

**Issue by Zero3K** [RequestPolicyContinued/subscriptions#65]
I tried allowing the domains I thought would allow them to be played. I managed to get the site to load but now it gives an error when trying to view a live stream/VOD An example of a VOD can be found at https://www.twitch.tv/videos/232107274. Please add the proper domains, etc. to the proper subscription list so Twitch can work out of the box. Thanks in advance.

**Comment by Zero3K** [comment]
I managed to get them working by adding an allow policy with the destination's scheme being set to mediasource and the other two text boxes having nothing in them.

**Comment by myrdd** [comment]
what's the list of rules you added?

**Comment by Zero3K** [comment]
Allow | *.twitch.tv | *.ajax.googleapis.com | User | x
Allow | *.siliconera.com | *.twitch.tv | User | x
Allow | *.embedly.com | *.twitch.tv | User | x
Allow | *.twitch.tv | *.twitchcdn.net | User | x
Allow |   | mediasource:<path> (host optional) | User | x

**Comment by myrdd** [comment]
> Allow | *.twitch.tv | *.twitchcdn.net | User | x

Yes, this is necessary. I'll add the subscription rule.

> Allow | *.twitch.tv | *.ajax.googleapis.com | User | x
> Allow |   | mediasource: (host optional) | User | x

I didn't have to add those rules when watching the url you've mentioned in the first post, https://www.twitch.tv/videos/232107274.

> Allow | *.siliconera.com | *.twitch.tv | User | x
> Allow | *.embedly.com | *.twitch.tv | User | x

These rules allow embedding twitch. We do not maintain "embed rules" right now.
