### ISSUE TITLE
Subscriptions: General discussion

### ISSUE THREAD

**Issue by nodiscc** [RequestPolicyContinued/subscriptions#7]
It would be good to define guidelines about what should/should not be included in official subscriptions; and whether we allow third party subscriptions. This was discussed at https://github.com/RequestPolicyContinued/requestpolicy/issues/339, https://github.com/RequestPolicyContinued/requestpolicy/issues/343, https://github.com/RequestPolicyContinued/requestpolicy/issues/510. 

(Having lots of rules in the default official subscrptions may harm peformance, make lists harder to maintain, and not benefit many users.)

Anyway, general discussion about subscriptions lists. Offtopic-but-related is also welcome.

**Comment by myrdd** [comment]
@nodiscc I've found and fixed a syntax error: https://github.com/RequestPolicyContinued/subscriptions/commit/468073bee74dceb95da9950ed2a5f0f02454df9c. Please check JSON syntax before committing. RP won't update the subscription if there's an error, e.g. this time the error was:
```
[RequestPolicy] [INFO] [INTERNAL] Failed to update subscription [Subscription official allow_functionality https://raw.githubusercontent.com/RequestPolicyContinued/subscriptions/master/official-allow_functionality.json]: SyntaxError: JSON.parse: unexpected character at line 176 column 2 of the JSON data
```

**Comment by marzametal** [comment]
How to export rules created by the user?... or even export settings altogether, similar to how the previous RequestPolicy extension handled it?

**Comment by nodiscc** [comment]
> How to export rules created by the user

They are stored in `~/.mozilla/firefox/*.default/requestpolicy/policies/user.json`.

**Comment by myrdd** [comment]
Hi @marzametal

> or even export settings altogether, similar to how the previous RequestPolicy extension handled it?

Afaik RP 0.5.x only exported the rules (origin rules, destination rules and origin-to-destination rules). If you would like to be able to export/import *settings*, please create a new issue in the [`requestpolicy` repo](https://github.com/RequestPolicyContinued/requestpolicy/issues).

By the way, questions and discussions about RP itself should be done not here but at https://github.com/RequestPolicyContinued/requestpolicy/issues/484.
